

supabase_url = "https://hxplmpowstdtprobmpqm.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4cGxtcG93c3RkdHByb2JtcHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTQyNzYwMzUsImV4cCI6MTk2OTg1MjAzNX0.yVW26ZrhAA449o0kiHMHlzjRYTAfB12ewJ6MxL3faUw"

# .streamlit/secrets.toml

[postgres]
host = "db.hxplmpowstdtprobmpqm.supabase.co"
port = 5432
dbname = "postgres"
user = "postgres"
password = "PNHvv228322"